version: '3.4'

services:
  transportscales.api:
    image: transportsc:latest
    build:
      context: .
      dockerfile: /Dockerfile
    
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=gfhfpbn0101
      - POSTGRES_DB=TransportScalesDb
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
       - 5432:5432
  
  frontend:
    image: scales:latest
    build:
      context: .
      dockerfile: /angular.Dockerfile